# theme: jekyll-theme-architect
theme: minima
title: Wunna Soe Notes
author: Wunna Soe
email: wunnasoe.hws@gmail.com
description: "ဝဏစိုး"

# social links
github_username:  mrwunnasoe
facebook_username: wunna.soe.31

show_excerpts: fale # set to false to remove excerpts on the homepage

---
title: "first-page"
date: 2020-05-18
---
